#ifndef _HEADER_H_
#define _HEADER_H_


#define PULSE_CODE _PULSE_CODE_MINAVAIL+1
#define MYNULL_HOGEHOGE_CODE 1
#define DCMD_MYNULL_HOGEHOGE __DIOT(_DCMD_MISC, MYNULL_HOGEHOGE_CODE, char[256])


#endif//_HEADER_H_
